name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        attr: [23-4, 24-1, 24-2, 24-3, 24-4, 24-5, 25-1, 25-2, 25-3, 26-1, 26-2, 26-3, 27-1, snapshot]
        exclude:
          - os: macos-latest
            attr: 23-4
          - os: macos-latest
            attr: 24-1
          - os: macos-latest
            attr: 24-2
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 24.5
    - run: curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python 
    - run: echo "::add-path::/Users/runner/.cask/bin"
    - run: ls
    - run: pwd
    - run: cask build
